### 1. Tes Registrasi User Baru
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
"username": "lutfisetiadi",
"email": "lutfi@ui.ac.id",
"password": "password123",
"role": "mahasiswa"
}

###

### 2. Tes Login User (Simpan Session ke Redis)
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
"email": "lutfi@ui.ac.id",
"password": "password123"
}

### 3. Tes Ambil Data Fasilitas
GET http://localhost:3000/api/facilities
Authorization: Bearer session_1_1781019603342

###

### 4. Tes Pengajuan Booking Fasilitas (Sesuai Kolom SQL Baru)
POST http://localhost:3000/api/bookings
Authorization: Bearer session_1_1781019603342
Content-Type: application/json

{
    "facility_id": 1,
    "tanggal_pinjam": "2026-06-15",
    "jam_mulai": "08:00:00",
    "jam_selesai": "11:00:00"
}

### ... (Kodingan tes 1 sampai 4 biarkan saja) ...

### 5. Tes Ambil Riwayat Booking Saya (Harus Bawa Token Redis)
GET http://localhost:3000/api/bookings/my
Authorization: Bearer session_1_1781019760184

### ... (Kodingan tes 1 sampai 5 biarkan saja) ...

### 6. Registrasi Akun Admin Kampus
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "username": "admin",
    "email": "akuadalahadmin@ui.ac.id",
    "password": "admin290",
    "role": "admin"
}

###

### 7. Login Akun Admin (Ambil Token Session Admin)
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "akuadalahadmin@ui.ac.id",
    "password": "admin290"
}

###

### 8. Akses Mengubah Status Booking (Harus Pakai Token Admin)
PATCH http://localhost:3000/api/admin/bookings/status
Authorization: Bearer session_3_1781020083632
Content-Type: application/json

{
    "booking_id": 1,
    "status": "Approved"
}